import { StatusCodes } from 'http-status-codes';

export const ErrorCodeMap: { [key: string]: number } = {
  API_VALIDATION_ERROR: StatusCodes.BAD_REQUEST,
  FORM_VALIDATION_ERROR: StatusCodes.BAD_REQUEST,
  INTERNAL_SERVER_ERROR: StatusCodes.INTERNAL_SERVER_ERROR,
  METHOD_NOT_ALLOWED_ERROR: StatusCodes.METHOD_NOT_ALLOWED,
  UNAUTHORIZED: StatusCodes.UNAUTHORIZED,
  UNIMPLEMENTED: StatusCodes.NOT_IMPLEMENTED,
  RESPONSE_VALIDATION_ERROR: StatusCodes.INTERNAL_SERVER_ERROR,
  ASSERTION_ERROR: StatusCodes.BAD_REQUEST,
  PRECONDITION_FAILED_ERROR: StatusCodes.PRECONDITION_FAILED,
  NOT_FOUND: StatusCodes.NOT_FOUND,
  CONFLICT: StatusCodes.CONFLICT,
  BAD_REQUEST: StatusCodes.BAD_REQUEST,
};

export const ErrorCodes = {
  API_VALIDATION_ERROR: 'API_VALIDATION_ERROR',
  FORM_VALIDATION_ERROR: 'FORM_VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  METHOD_NOT_ALLOWED_ERROR: 'METHOD_NOT_ALLOWED_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNIMPLEMENTED: 'UNIMPLEMENTED',
  RESPONSE_VALIDATION_ERROR: 'RESPONSE_VALIDATION_ERROR',
  ASSERTION_ERROR: 'ASSERTION_ERROR',
  PRECONDITION_FAILED_ERROR: 'PRECONDITION_FAILED_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  BAD_REQUEST: 'BAD_REQUEST',
};
